version: '2.4'

services:
  jekyll:
    image: jekyll/jekyll:latest
    environment:
      - JEKYLL_ENV=dev
    command: jekyll serve --watch --force_polling --verbose --config _config.dev.yml
    ports:
      - '4000:4000'
    volumes:
      - .:/srv/jekyll